//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class matrixdata
    {
        public int ID { get; set; }
        public int MATRIX_N { get; set; }
        public int X_POS { get; set; }
        public int Y_POS { get; set; }
        public int VALUE { get; set; }
    }
}
